### ISSUE TITLE
Link to GitHub repo

### ISSUE THREAD

**Issue by peterpeterparker** [infu/icblast#2]
Hi 👋

I just followed your tweet link about your recent update (coolio) and, noticed that no link to the repo was displayed on [Blast](https://jglts-daaaa-aaaai-qnpma-cai.ic0.app/). So though about sharing that it could be maybe cool to add such a GitHub link to the frontend app.

P.S.: Not sure if there is no such link, not sure if it's a cool idea and where you would like to add it, that's why I did not provided a PR directly 😉

**Comment by infu** [comment]
Hey!

There is a link when you click the 'i' button, but I should probably put a github icon and make it more visible.

**Comment by peterpeterparker** [comment]
Oh yeah, totally missed it. Maybe also make it a link would be neat.

**Comment by infu** [comment]
I am going to attempt to remake the whole frontend using a better platform :)

**Comment by peterpeterparker** [comment]
Go big or go home, I like the spirit 😉👍
